### ISSUE TITLE
Hit boxes too big, can't get around 1x1 obstacles without dying

### ISSUE THREAD

**Issue by karlin88** [alyssalina/catsandbeer#28]
![image](https://user-images.githubusercontent.com/20197984/31578654-65ff58dc-b0da-11e7-8514-8e62685ad369.png)

**Comment by karlin88** [comment]
found hit box debug code
http://www.html5gamedevs.com/topic/4227-decrease-collision-box-size/

**Comment by SoundBlasterPro** [comment]
Made the sprite box slightly smaller than the actual character to make collisions with walls, collectibles, and enemies more natural/intuitive
