### ISSUE TITLE
Research on how to build games in Javascript

### ISSUE THREAD

**Issue by alyssalina** [alyssalina/catsandbeer#3]
Research general features we want to do:
-Moving characters around
-Collecting stuff
-Tying in back-end database for collection

**Comment by yfzwinnie** [comment]
We can use the following resource as a guide to build the initial phase of Cats and Beer: https://eloquentjavascript.net/15_game.html
http://www.lessmilk.com/

Here is a good start to build level 1: http://www.lessmilk.com/tutorial/2d-platformer-phaser

Example of a similar game: http://www.lessmilk.com/game/dark-blue/

**Comment by yfzwinnie** [comment]
Best tutorial for a simple game so far: https://mozdevs.github.io/html5-games-workshop/

Will tweak this to catsandbeer, add more levels, etc.
